POST http://localhost:8080/fruit/product/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="productsFile"; filename="products.csv"
Content-Type: text/csv

< ./products.csv
--WebAppBoundary--

### add to cart
POST http://localhost:8080/fruit/cart
Content-Type: application/x-www-form-urlencoded

id=12

### login
POST http://localhost:8080/fruit/login
Content-Type: application/x-www-form-urlencoded

username=user&pwd=password



